### ISSUE TITLE
Getis Spatial Filter in this package?

### ISSUE THREAD

**Issue by jfsantosm** [r-spatial/spatialreg#20]
Hello,

I have been working on an R function script that uses the Getis filter to remove the spatial component of variables, and I am wondering if it could be added to the spatialreg package or it is better suited for other packages such as spdep. I have never contributed to a package, but I would love to document the function and do what is needed for it to be used by other scientists/users.

Thanks in advance for your guidance.
Best regards,

Felipe

**Comment by rsbivand** [comment]
Thanks for your interest. Since `SpatialFiltering()` and `ME()` are in **spatialreg**, that is possibly more appropriate than **spdep**. So a pull request with the code and its documentation would be welcome, preferably not involving any other packages than itself and **spdep**, documentation not as roxygen markup but only as an Rd file. An example corresponding to an original article with a small data set (or columbus) in the documentation would be helpful.

**Comment by jfsantosm** [comment]
Thanks for your prompt reply! I will do so!
Best,
Felipe
