### ISSUE TITLE
regression models use all cores, cannot set. 

### ISSUE THREAD

**Issue by thecrobe** [r-spatial/spatialreg#21]
Hi, 

I am working on some spatial regression models using the errorsarlm() function. Unfortunatly it seems that this function uses all cores on a computer even when it is previously limited to a subset using the parallel package. I was hoping there is a way to either set the number of cores in the funciton itself or reoslve this. 

Many thanks! 

Justin

**Comment by rsbivand** [comment]
Please provide a full reproducible example. 

My guess is that, since `errorsarlm()` does not  use any **parallel** facilities at  all (explicit parallelism https://cran.r-project.org/web/views/HighPerformanceComputing.html), you are actually seeing the effect of your use of parallel BLAS (implicit parallelism), which is not controlled by **parallel**. 

`errorsarlm()` does call BLAS functions, and if your BLAS is parallel, it will use the number of cores available, or possibly permit the number to be controlled by for example https://cran.r-project.org/package=RhpcBLASctl.
