### ISSUE TITLE
should W2X = FALSE by default?

### ISSUE THREAD

**Issue by JosiahParry** [r-spatial/spatialreg#55]
I was comparing implementations of S2SLS between pysal and spatialreg and I was _very_ confused as to why the estimates were different between the two. It turns out that `{spatialreg}` uses second order spatially lagged variables _by default_ which I was quite surprised by. Would it make more sense for `W2X` to be `FALSE` by default? 

https://github.com/r-spatial/spatialreg/blob/93683eddb9e9d3bc6582137b4c1e4719226dd972/R/s2sls.R#L5

In Anselin & Rey (p 161) 

> " This expression would suggest the use of several orders of spatially lagged explanatory variables as instruments, e.g. $WX$, $W^2X$, etc. This is the approach taken in `GeoDaSpace` and `spreg`, where only first order spatial lags are the default (second order spatial lags can be specified as an option)."

For full context the equation referenced is: 

$$
E[W_y |X] = W (\sum_{p=0}^{\infty} \rho^pW^p)X\beta
$$

and the ^p is the suggestion of "several orders"

I think part of the reason it _feels_ better is that I struggle to understand the interpretation of $\rho$ when we are using higher order lags as the instruments.

**Comment by rsbivand** [comment]
@JosiahParry No, it has been this way since March 2010, and is as reported in https://www.jstatsoft.org/article/view/v063i18, eq. 12, p. 9. This matches eq. 2.2.3.4, p. 34 in Kelejian & Piras (2017), and specifically their comment at the foot of the page and its footnote:

> For estimation, researchers often take r (your p) = 2.

@gpiras would you agree? In any case, this estimator is really superseded by those in `sphet`.

**Comment by JosiahParry** [comment]
Thanks! I forgot about {sphet} I'll go peek over there :)
